services:

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: tiaocarreiro
      DB_USERNAME: postgres
      DB_PASSWORD: 1234

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/app
      - /app/node_modules   # <- volume anônimo para preservar dependências
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: tiaocarreiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
